[theme]
base = "light"
primaryColor = "#17623f"
backgroundColor = "#f4f8f7"
secondaryBackgroundColor = "#ffffff"
textColor = "#101831"
font = "sans-serif"
baseFontSize = 15
baseRadius = "8px"
buttonRadius = "7px"
borderColor = "#e2e9ed"
showWidgetBorder = true
headingFontSizes = ["38px", "25px", "21px", "18px", "16px", "14px"]
headingFontWeights = [700, 600, 600, 600, 600, 600]

[theme.sidebar]
backgroundColor = "#103e2c"
secondaryBackgroundColor = "#275d44"
textColor = "#e9f3ed"
primaryColor = "#a4d78e"
borderColor = "#3a6754"
